FROM python:3.6

ENV PYTHONUNBUFFERED 1

ADD . /app
WORKDIR /app

COPY ./docker/requirements.txt ./app/requirements.txt
RUN pip install --upgrade pip
RUN pip install -r ./app/requirements.txt

ENV FLASK_ENV development

EXPOSE 6002

CMD python app/app.py